name: aig-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.0
  - pandas=2.2
  - scikit-learn=1.5
  - scipy=1.14
  - matplotlib=3.9
  - seaborn=0.13
  - pyarrow=17.0
  - jupyterlab=4.2
  - pip
