""" added is_active in Tenant Model

Revision ID: 041bd9a12737
Revises: 4686ecdd07a1
Create Date: 2025-06-21 19:28:03.900178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041bd9a12737'
down_revision = '4686ecdd07a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
