"""Add preferred_mfa to User

Revision ID: 057e27f089c6
Revises: 1211f7019227
Create Date: 2025-07-16 14:26:04.791168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057e27f089c6'
down_revision = '1211f7019227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_mfa', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_mfa')

    # ### end Alembic commands ###
