"""Remove enforce_strict_mfa from TenantUser

Revision ID: 1211f7019227
Revises: 2ec9239813b4
Create Date: 2025-07-04 22:13:11.228235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1211f7019227'
down_revision = '2ec9239813b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.drop_column('enforce_strict_mfa')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enforce_strict_mfa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('enforce_strict_mfa')

    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enforce_strict_mfa', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
