"""Make credential_id tenant-scoped unique

Revision ID: 2a1f68044891
Revises: d186b1e2c39f
Create Date: 2025-07-03 17:42:03.013587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1f68044891'
down_revision = 'd186b1e2c39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.drop_constraint('webauthn_credentials_credential_id_key', type_='unique')
        batch_op.create_unique_constraint('uq_credential_per_tenant', ['credential_id', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.drop_constraint('uq_credential_per_tenant', type_='unique')
        batch_op.create_unique_constraint('webauthn_credentials_credential_id_key', ['credential_id'])

    # ### end Alembic commands ###
