"""Add enforce_strict_mfa to Tenant

Revision ID: 2ec9239813b4
Revises: c55de93a5aca
Create Date: 2025-07-04 21:52:19.201548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec9239813b4'
down_revision = 'c55de93a5aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enforce_strict_mfa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.drop_column('enforce_strict_mfa')

    # ### end Alembic commands ###
