"""Add otp_secret and otp_email_label to TenantUser

Revision ID: 34e6717d81a1
Revises: 2ba407361fc1
Create Date: 2025-06-17 18:04:47.377398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e6717d81a1'
down_revision = '2ba407361fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('otp_email_label', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.drop_column('otp_email_label')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
