"""Add abuse tracking fields to Tenant

Revision ID: 62c6437cb3de
Revises: 994880a18043
Create Date: 2025-06-23 14:56:39.861028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c6437cb3de'
down_revision = '994880a18043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_request_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_error_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('api_last_reset', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('api_last_reset')
        batch_op.drop_column('api_score')
        batch_op.drop_column('api_error_count')
        batch_op.drop_column('api_request_count')

    # ### end Alembic commands ###
