"""added password history

Revision ID: 721003e78e42
Revises: 52b6bec1c801
Create Date: 2025-04-21 20:15:39.085084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721003e78e42'
down_revision = '52b6bec1c801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_history')
    # ### end Alembic commands ###
