"""Add HeadquartersWallet model

Revision ID: 78131fa191bb
Revises: 19961ef7425e
Create Date: 2025-04-01 18:10:45.910012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78131fa191bb'
down_revision = '19961ef7425e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headquarters_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('headquarters_wallet')
    # ### end Alembic commands ###
