"""Add otp_secret to User model

Revision ID: 885568c6e4bb
Revises: 988e8be9bbef
Create Date: 2025-03-31 16:26:59.410388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885568c6e4bb'
down_revision = '988e8be9bbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
