"""Updated SIMCard model and User-SIM relationship

Revision ID: 9316e6360b6c
Revises: 4ef3f44c7265
Create Date: 2025-03-11 17:09:31.315947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9316e6360b6c'
down_revision = '4ef3f44c7265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iccid', sa.String(length=20), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('network_provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('registered_by', sa.String(length=100), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iccid'),
    sa.UniqueConstraint('mobile_number')
    )
    op.drop_table('sim_registrations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_mobile_number_key', type_='unique')
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_mobile_number_key', ['mobile_number'])

    op.create_table('sim_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sim_registrations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sim_registrations_pkey')
    )
    op.drop_table('sim_cards')
    # ### end Alembic commands ###
