"""Fix user_roles uniqueness per tenant

Revision ID: 938575364f81
Revises: 770a0b6867c6
Create Date: 2025-04-26 15:52:02.332617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938575364f81'
down_revision = '770a0b6867c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('user_roles_role_name_key', type_='unique')
        batch_op.create_unique_constraint('uq_role_per_tenant', ['role_name', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_per_tenant', type_='unique')
        batch_op.create_unique_constraint('user_roles_role_name_key', ['role_name'])

    # ### end Alembic commands ###
