"""Switch HQ wallet balance to Numeric

Revision ID: 994880a18043
Revises: d7d95fce8435
Create Date: 2025-06-23 12:40:43.188327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994880a18043'
down_revision = 'd7d95fce8435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('headquarters_wallet', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('headquarters_wallet', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
