"""Added TenantPasswordHistory

Revision ID: a7a84d4bd655
Revises: 62c6437cb3de
Create Date: 2025-06-25 16:48:09.782639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a84d4bd655'
down_revision = '62c6437cb3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_user_id'], ['tenant_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_password_history')
    # ### end Alembic commands ###
