"""Added otp_email_label to User model

Revision ID: b0668abe23d8
Revises: 74e3c85c5c65
Create Date: 2025-04-05 10:43:25.026376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0668abe23d8'
down_revision = '74e3c85c5c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_email_label', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_email_label')

    # ### end Alembic commands ###
