"""Add preferred_mfa to TenantUser

Revision ID: c55de93a5aca
Revises: 2a1f68044891
Create Date: 2025-07-04 07:31:45.018397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55de93a5aca'
down_revision = '2a1f68044891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_mfa', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.drop_column('preferred_mfa')

    # ### end Alembic commands ###
