"""Added expiry date for API-KEY

Revision ID: deb458efb128
Revises: a7a84d4bd655
Create Date: 2025-06-28 09:28:39.652136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb458efb128'
down_revision = 'a7a84d4bd655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('api_key_expires_at')

    # ### end Alembic commands ###
